# Generated by Django 5.1.7 on 2025-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_name_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isTop',
            field=models.BooleanField(default=False),
        ),
    ]
